import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  // 前端
  "/HTML/": [
    "W3C和Web标准",
    "DOCTYPE",
    "标准模式和怪异模式",
    "H5和HTML5",
    "HTML语义化",
    "块级元素和行内元素",
    "HTML标签",
    "link和@import",
    "src和href",
    "title和alt",
    "常用的图片格式",
    "iframe",
    "meta",
    "SEO",
    "微格式",
    "网页开发和小程序开发",
    "实现在图片的某个区域做到点击事件",
    "前端开发必记单词",
    "企业网站搭建的步骤",
  ],
  "/CSS/": [
    "CSS样式书写方式",
    "CSS选择器",
    "CSS选择器优先级",
    "初始化CSS样式",
    "CSS预处理器",
    "BFC",
    "IFC",
    "盒模型",
    "包含块",
    "float",
    "清除浮动",
    "position",
    "层叠上下文",
    "display",
    "flex",
    "float和position和display",
    "margin和padding",
    "margin重叠",
    "伪类与伪元素",
    "伪类LVHA",
    "widthauto和width100",
    "font-style属性中italic和oblique",
    "visibility属性",
    "CSS中可以继承的属性",
    "CSS3新特性",
    "CSS3的all",
    "CSS3新伪类",
    "hasLayout",
    "媒体查询",
    "div居中",
    "双飞翼和圣杯布局",
    "满屏品字布局",
    "瀑布流布局",
    "CSS多列等高",
    "全屏滚动的原理",
    "纯CSS创建一个三角形的原理",
    "元素竖向的百分比设定是相对于容器的高度吗",
    "li与li之间存在空白间隔的原因及解决办法",
    "CSS使页面里的字体变清晰、变细",
    "修改chrome记住密码后自动填充表单的黄色背景",
    "让chrome支持小于12px的文字",
    "网页中应该使用奇数还是偶数的字体",
    "图片base64编码",
    "实现网页变灰效果",
    "实现视差滚动效果的网页",
    "CSS优化、提高性能的方法",
    "抽离样式模块",
    "经常遇到的浏览器兼容性问题",
    "设备像素、css 像素、设备独立像素、dpr、ppi",
    "layout viewport、visual viewport 和 ideal viewport",
    "大厂是怎么做移动端适配的",
    "6种移动端1px解决方案",
  ],
  "/JAVASCRIPT/": [
    "数据类型",
    "判断数据类型",
    "包装类",
    "预解析和变量提升",
    "暂时性死区",
    "浮点数精度",
    "数组的原生方法",
    "forEach和map",
    "forEach跳出循环",
    "arguments",
    "数组合并和对象合并",
    "数组和函数在内存中的存储",
    "深拷贝和浅拷贝",
    "箭头函数",
    "立即执行函数",
    "柯里化",
    "作用域和作用域链",
    "闭包",
    "防抖和节流",
    "内存泄漏",
    "v8垃圾回收机制",
    "原型和原型链",
    "继承",
    "this",
    "call和apply和bind",
    "new操作符",
    "事件捕获事件冒泡",
    "事件委托",
    "ajax",
    "常见的请求方式",
    "跨域",
    "fetch",
    "并发、并行、异步、同步",
    "promise",
    "AbortController和AbortSignal",
    "generator",
    "async await",
    "事件循环机制",
    "setTimeout和setImmediate和process.nextTick",
    "本地存储",
    "CommonJS和ES6",
    "一次渲染10w条数据",
    "移动端上拉加载下拉刷新",
    "WebWorker",
    "WebSocket",
    "IntersectionObserver",
    "图片懒加载",
    "分片上传",
    "分片加载",
    "localhost和127.0.0.1的区别",
    "从输入一个url到浏览器页面展示经历哪些过程",
    "页面重定向",
    "URL地址转码与解码",
    "捕获异常",
    "前端监控",
    "进程和线程",
    "长链接方案",
    "代码执行结果",
    "ES6",
    "ES7到ES13",
    "jquery",
  ],
  "/VUE/": [
    "vue本身的数据管理是什么样的",
    "单项数据流",
    "props和data",
    "computed和methods",
    "computed和watch",
    "组件中的data为什么必须是一个函数",
    "组件中的key",
    "v-if和v-show",
    "v-if和v-for优先级",
    "ref属性",
    "slot插槽",
    "scoped",
    "样式穿透（CSS穿透）",
    "nextTick",
    "keep alive",
    "vue内置指令",
    "vue生命周期",
    "vue组件通信",
    "vuex",
    "pinia",
    "路由模式",
    "解决打包后路由没显示出来的问题（history 404）",
    "路由传参",
    "vue动态路由",
    "路由守卫",
    "router、routes、route",
    "vue自动配置路由",
    "vue环境变量和模式",
    "vue设置代理",
    "vue部署应用包时的基本URL",
    "vue3",
    "vue3的Composition API",
    "vue3为什么使用Proxy",
    "vue响应式",
    "vue中的虚拟DOM",
    "vue路由原理",
    "vue编译原理",
    "diff算法",
    "手写diff算法",
    "手写代码vue2",
    "vue源码深入剖析",
    "vue3核心源码解析",
    "SPA和MPA",
    "mvvm和mvc",
    "vue性能优化",
    "vue首屏渲染优化",
    "将package.json中的所有依赖项更新到最新版本",
    "vue项目中遇到的困难",
    // 2025
    "2025-01.谈谈你对vue的理解",
    "2025-02.谈谈你对SPA的理解",
    "2025-03.vue为什么需要虚拟DOM",
    "2025-04.谈一谈对vue组件化的理解", // 组件化和模块化的区别
    "2025-05.vue为什么需要diff检测差异",
    "2025-06.请说一下你对响应式数据的理解",
    "2025-07.vue中如何检测数组变化",
    "2025-08.vue中如何进行依赖收集",
    "2025-09.vue.set方法是如何实现的",
    "2025-10.vue中的v-show和v-if怎么理解",
    "2025-11.computed和watch的区别",
    "2025-12.解释ref和reactive的区别",
    "2025-13.watch和watchEffect的区别",
    "2025-14.如何将template转换成render函数",
    "2025-15.new Vue()这个过程究竟做了些什么",
    "2025-16.vue.observable",
    "2025-17.v-if和v-for的优先级",
    "2025-18.vue的生命周期方法",
    "2025-19.vue中diff算法原理",
    "2025-20.说明vue中key的作用和原理",
    "2025-21.vue.use方法的作用",
    "2025-22.vue.extend方法的作用",
    "2025-23.vue组件中的data为什么必须是一个函数",
    "2025-24.函数组件的优势",
    "2025-25.vue中的过滤器",
    "2025-26.v-once",
    "2025-27.vue.mixin",
    "2025-28.vue中slot",
    "2025-29.双向绑定",
    "2025-30.vue中.sync修饰符",
    "2025-31.vue中递归组件",
    "2025-32.组件中写name选项有哪些好处",
    "2025-33.vue常用的修饰符",
    "2025-34.自定义指令",
    "2025-35.vue中nextTick",
    "2025-36.keep-alive",
    "2025-37.vue中使用了哪些设计模式",
    "2025-38.vue中的性能优化",
    "2025-39.vue单页应用首屏加载速度慢的优化方法",
    "2025-40.vue项目中跨域问题的解决方法",
    "2025-41.vue项目中封装axios",
    "2025-42.vue项目中做权限控制",
    "2025-43.vue中异步组件的作用及原理",
    "2025-44.vue路由的钩子函数",
    "2025-45.vue项目中错误处理",
    "2025-46.vue3中模板编译优化",
  ],
  "/REACT/": [
    "对react的理解",
    "react本身的数据管理是什么样的",
    "受控组件和非受控组件",
    "函数组件和类组件",
    "高阶组件",
    "element和component和instance",
    "合成事件",
    "setState过程",
    "setState是同步还是异步",
    "为什么有时连续两次setState只有一次生效",
    "值捕获特性",
    "JSX",
    "react中的虚拟DOM",
    "虚拟DOM一定更快吗",
    "组件中的key",
    "react中如何避免不必要的render",
    "PureComponent",
    "react生命周期",
    "react组件通信",
    "react的context",
    "mobx",
    "react实现keep-alive",
    "react中的渲染流程",
    "fiber",
    "异步渲染和fiber",
    "react性能优化",
    "react异常处理",
  ],
  "/UNIAPP和WX/": [
    "uniapp和vue",
    "使用promise封装uni.request请求",
    "weixinjs-sdk",
    "微信小程序生命周期",
    "微信小程序支付详细流程",
    "小程序分包",
  ],
  // 后端
  "/NODE/": [],
  // 数据库
  // 可视化
  "/CANVAS/": [
    "canvas2d",
  ],
  "/WEBGL/": [],
  "/ECHARTS/": [],
  // 工具
  "/TOOL/": [
    "mac下管理node多版本工具",
    "git分支管理"
  ],
  // 产品与UI设计
  "/产品与UI设计/": [
    "figma",
    "APP开发之账号注册方式"
  ],
  // 问题
  "/BUGS/": [
    "防止按钮重复点击",
    "window.open打开链接修改窗口标题",
    "移动端上拉加载分页数据时，删除一条数据导致的问题",
    "无缝轮播",
    "button中嵌套navigator不能跳转",
    "h5唤起app",
    "文件夹上传",
    "password input浏览器自动填充密码",
    "js超过Number最大值的数怎么处理",
    "如何解决页面请求接口大规模并发问题",
    "大文件上传",
    "在前端怎么实现页面截图",
    "移动端适配问题如何解决",
    "如何修改第三方npm包",
    "使用同一个链接，实现PC打开是web应用，手机打开是h5应用",
    "当QPS达到峰值时，该如何处理",
    "如何实现网页加载进度条",
    "前端水印功能",
    "web应用中如何对静态资源加载失败的场景做降级处理",
    "怎样设计一个全站请求耗时统计工具",
    "说说对函数式编程思想的理解",
    "说说对DNS协议的理解",
    "怎么实现一个电影票选座功能",
    "说说图片性能优化的方案",
    "移动端上拉加载，下拉刷新实现方案",
    "深度SEO优化",
    "在window对象上频繁绑定内容，有什么风险",
    "服务端渲染（SSR）与前后端同构技术原理揭秘",
    // "SSG和SSR的区别",
    "前端大屏",
    "前端直播技术",
    "base64、url、blob互相转换",
  ],
  "/PHP/": [
    "基础知识",
    "yii2",
    "-> 、=>、::、$this->四种符号"
  ]
});
